### ISSUE TITLE
Move away from a vm

### ISSUE THREAD

**Issue by AMTitan** [salatine/ricing.online#58]
I load the page and it takes over minute to load to see this 
![image](https://github.com/salatine/ricing.online/assets/29708070/257078e0-04b1-4ecb-b46d-46f2e97df357)
I would say you should move away from a vm, and potentially move towards using javascript to edit some items in the dom to show how it would look. Sending almost 95mb to the user can feel pretty quick when you are running it on localhost, but when someone is visiting your website, this is very heavy. The worst part is that the 60mb debian file that is sent to the user is not cached by many browsers as it is too big, requiring the user to almost wait the exact same amount of time to update how the page looks. You could convert it simply into a structure like this:

```html
<div id="preview">
	<div id="bar">
		<div id="bar-left">1 2 3 4 5 6 7 8 9</div>
		<div id="bar-right">19:53:12</div>
	</div>
	<div id="window"></div>
</div>
```

then you could use some css like this:

```css
#preview {
	background-image: url("https://ricing.online/example_background_image.png");
	width: 1920;
	height: 1080px;
	
	/*could be used to preserve how it looks but make it smaller if needed*/
	 zoom: 0.5; 
    -moz-transform: scale(0.5); 
    -moz-transform-origin: 0 0;
}

#bar {
	position: relative;
	top: 0;
	height: 24px;
	background-color: black;
	font: 12px Lato; /*depending on the font used you will have to import it*/
	color: white;
}

#bar-left {
	float: left;
}

#bar-right {
	float: right;
}

#window {
	background-image: url("https://ricing.online/image_of_firefox_or_something");
	border-style: solid;
	border-width: 2px;
	border-radius: 12px;
	border-color: grey;
	margin: 8px;
}

#window:hover {
	border-color: green;
}
```

This is just something I made pretty quickly, but I hope you see the idea. These elements would be changed automatically when the user updates there values.
